# Generated by Django 2.2.4 on 2019-09-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_auto_20190920_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
