# Generated by Django 2.2.4 on 2019-09-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_auto_20190920_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='user_limit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
