# Generated by Django 2.2.4 on 2019-09-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0006_auto_20190923_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
