# Generated by Django 2.2.3 on 2019-09-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0007_auto_20190924_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='user_limit',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
