# Generated by Django 2.2.4 on 2020-01-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0009_merge_20200116_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='is_hyperlinked',
            field=models.BooleanField(default=False),
        ),
    ]
