# Generated by Django 2.2.4 on 2022-02-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0010_program_is_hyperlinked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=100000),
        ),
    ]
