# Generated by Django 2.2.4 on 2020-01-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attestation_url', models.CharField(max_length=255, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('is_scan_in', models.BooleanField(default=False, null=True)),
                ('is_scan_out', models.BooleanField(default=False, null=True)),
                ('role', models.CharField(max_length=255, null=True)),
                ('scan_in_date_time', models.CharField(max_length=255, null=True)),
                ('scan_out_date_time', models.CharField(max_length=255, null=True)),
                ('session_id', models.BigIntegerField(null=True)),
                ('user_id', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('notification_type', models.CharField(max_length=255, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('role', models.CharField(max_length=255, null=True)),
                ('user_id', models.CharField(max_length=255, null=True)),
                ('session_id', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('program_name', models.CharField(max_length=255, null=True)),
                ('session_creator', models.CharField(max_length=255, null=True)),
                ('session_description', models.TextField(null=True)),
                ('session_end_date', models.CharField(max_length=255, null=True)),
                ('session_name', models.CharField(max_length=255, null=True)),
                ('session_start_date', models.CharField(max_length=255, null=True)),
                ('session_status', models.IntegerField()),
                ('program_id', models.BigIntegerField(null=True)),
                ('topic_id', models.BigIntegerField(null=True)),
                ('training_organization', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'session',
            },
        ),
    ]
