# Generated by Django 2.2.4 on 2022-02-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session_Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_url', models.CharField(max_length=255, null=True)),
                ('user_id', models.CharField(max_length=255, null=True)),
                ('session_id', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'session_links',
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='description',
            field=models.CharField(max_length=100000, null=True),
        ),
    ]
