# Generated by Django 2.2.3 on 2019-09-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_auto_20190925_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='pin_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
