# Generated by Django 2.2.4 on 2019-09-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_auto_20190925_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='pin_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
