# Generated by Django 2.2.4 on 2020-01-16 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0003_auto_20190926_1155'),
        ('entity', '0003_auto_20190926_0849'),
    ]

    operations = [
    ]
